/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/Home/HomeActivity/Activity.vue')['default']
    ActivityCard: typeof import('./src/components/Home/HomeActivity/ActivityCard.vue')['default']
    AdvertisementCard: typeof import('./src/components/Home/HomeRecommend/AdvertisementCard.vue')['default']
    AttentionCard: typeof import('./src/components/Home/HomeAttention/AttentionCard.vue')['default']
    LeftPopup: typeof import('./src/components/Home/HomePopupNav/LeftPopup.vue')['default']
    NoteCard: typeof import('./src/components/Home/HomeRecommend/NoteCard.vue')['default']
    NoteDetail: typeof import('./src/components/NoteDetail/NoteDetail.vue')['default']
    NoteDetailCard: typeof import('./src/components/NoteDetail/NoteDetailCard.vue')['default']
    NotesCard: typeof import('./src/components/Home/HomeNotes/NotesCard.vue')['default']
    RecipeCard: typeof import('./src/components/Home/HomeRecommend/RecipeCard.vue')['default']
    RecipeDetail: typeof import('./src/components/RecipeDetail/RecipeDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRecipeCard: typeof import('./src/components/Search/SearchNav/SearchRecipe/SearchRecipeCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
