/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/Home/HomeActivity/Activity.vue')['default']
    ActivityCard: typeof import('./src/components/Home/HomeActivity/ActivityCard.vue')['default']
    AdvertisementCard: typeof import('./src/components/Home/HomeRecommend/AdvertisementCard.vue')['default']
    AttentionCard: typeof import('./src/components/Home/HomeAttention/AttentionCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftPopup: typeof import('./src/components/Home/HomePopupNav/LeftPopup.vue')['default']
    NoteCard: typeof import('./src/components/Home/HomeRecommend/NoteCard.vue')['default']
    NotesCard: typeof import('./src/components/Home/HomeNotes/NotesCard.vue')['default']
    RecipeCard: typeof import('./src/components/Home/HomeRecommend/RecipeCard.vue')['default']
    RecipeClassifyCard: typeof import('./src/components/Recipe/RecipeClassifyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHomepage: typeof import('./src/components/Search/SearchHomepage.vue')['default']
    SearchRecipeCard: typeof import('./src/components/Search/SearchNav/SearchRecipe/SearchRecipeCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLeftPopup: typeof import('vant/es')['LeftPopup']
    VanLis: typeof import('vant/es')['Lis']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRecipeClassifyCard: typeof import('vant/es')['RecipeClassifyCard']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
