/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/BlogPostsView/ArticleList.vue')['default']
    AutoResizerTable: typeof import('./components/ModalTableDialog/AutoResizerTable.vue')['default']
    Chart: typeof import('./components/Overview/Chart.vue')['default']
    Comment: typeof import('./components/Overview/Comment.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Files: typeof import('./components/LocalFilesView/Files.vue')['default']
    Gather: typeof import('./components/Overview/Gather.vue')['default']
    Grouping: typeof import('./components/Grouping.vue')['default']
    GroupingTag: typeof import('./components/Grouping/GroupingTag.vue')['default']
    Label: typeof import('./components/BlogPostsView/Label.vue')['default']
    Line: typeof import('./components/Overview/Chart/Line.vue')['default']
    ModalTableDialog: typeof import('./components/ModalTableDialog.vue')['default']
    Pie: typeof import('./components/Overview/Chart/Pie.vue')['default']
    PrivateMessage: typeof import('./components/PrivateMessage.vue')['default']
    Reply: typeof import('./components/Overview/Comment/Reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topic: typeof import('./components/Topic.vue')['default']
    Upload: typeof import('./components/LocalFilesView/Upload.vue')['default']
    WhiteContainer: typeof import('./components/WhiteContainer.vue')['default']
  }
}
